name: Java CI with Maven and Test Coverage with JaCoCo

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build_and_test_backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest

    steps:
      # Step 1 to checkout the code from the repository
      - uses: actions/checkout@v4
      
      # Step 2 to set up Java JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'oracle'
          # https://github.com/marketplace/actions/setup-java-jdk#supported-distributions
      
      # Step 3 to build the backend with Maven
      - name: Build
        working-directory: backend/
        run: mvn -B package --file pom.xml

      # Step 4 Test the Backend
      - name: Test
        working-directory: backend/
        run: mvn clean verify

      # Step 5: Upload JaCoCo Report
      - name: Upload JaCoCo report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: backend/target/site/jacoco # Path to the HTML report directory
